#
# Makefile for Chapter 06
#
# Type  make    to compile all the programs
# in the chapter 
#
all: play_again3 rotate sigdemo1

clean:
	rm -f play_again3 rotate sigdemo1 

play_again3: play_again3.c
	cc -o play_again3 play_again3.c


rotate: rotate.c 
	cc -o rotate rotate.c 

sigdemo1: sigdemo1.c
	cc -o sigdemo1 sigdemo1.c


